---
deployment:
  tasks:
    - export SRCDIR=$PWD/webSyS
    - export DEPLOYPATH=/home/serviciosysistem/public_html/pruebagit
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -R "$SRCDIR"/* "$DEPLOYPATH"/
    - /bin/echo "Deployed on $(/bin/date)" > "$DEPLOYPATH"/version.txt
