---
deployment:
  tasks:
    - export DEPLOYPATH=/home/serviciosysistem/pruebagit.serviciosysistemas.com.ar
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -av --delete \
        --exclude ".git" \
        --exclude ".gitignore" \
        --exclude "node_modules" \
        ./ "$DEPLOYPATH"/
    - /bin/echo "Deployed on $(/bin/date)" > "$DEPLOYPATH"/version.txt
    - /bin/chmod 644 "$DEPLOYPATH"/version.txt